blank_issues_enabled: false
contact_links:
- name: 🙋🏾 Question
  url: https://github.com/percona/everest/discussions/new
  about: If you need help debugging something or have a general question about Everest