name: "💡 Feature Request"
description: If you have a suggestion for how to improve Everest
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form as completely as possible.

        Before submitting, please search to see if an issue already exists for the feature you are suggesting:
        - [Search GitHub Issues](https://github.com/percona/everest/issues)
        - [Search JIRA Issues](https://perconadev.atlassian.net/issues/?jql=project+%3D+%22EVEREST%22+ORDER+BY+created+DESC&atlOrigin=eyJpIjoiYjI2ZDMzYzNlN2I2NGFkYzk2Zjg1MzEzMzkyN2M0ZjIiLCJwIjoiaiJ9)

  - type: textarea
    attributes:
      label: What problem are you trying to solve?
      description: A concise description of what the problem is.
      placeholder: I have an issue when [...]
    validations:
      required: true

  - type: textarea
    attributes:
      label: How should the problem be solved?
      description: What do you expect to happen? Add any considered drawbacks.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Any alternatives you've considered?
      description: Is there another way to solve this problem that isn't as good a solution?

  - type: textarea
    attributes:
      label: How would users interact with this feature?
      description: If you can, explain how users will be able to use this.
