---
name: Feature build (PR)
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]

jobs:
  feature-build:
    name: Feature build
    if: contains(github.event.pull_request.labels.*.name, 'feature-build')
    uses: ./.github/workflows/feature-build.yaml
    with:
      vs_branch: ${{ github.event.pull_request.head.ref }}
      helm_branch: ${{ github.event.pull_request.head.ref }}
      everest_branch: ${{ github.event.pull_request.head.ref }}
      everest_operator_branch: ${{ github.event.pull_request.head.ref }}
      everest_catalog_branch: ${{ github.event.pull_request.head.ref }}
      artifacts_retention_days: 30
    secrets: inherit
